config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books, only: [:show] do
    resources :watch_lists, only: [:create, :destroy], shallow: true
  end
  
  get 'watchlist', to: 'watch_lists#index', as: :watchlist
  resources :deals, only: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :watch_lists
  has_many :deals
  has_one_attached :photo
  # validates :title, presence: true, uniqueness: true
  validates :language, presence: true
  validates :author, presence: true

  include PgSearch::Model
  pg_search_scope :search_book,
    against: {title: 'A' , author: 'B'},
    using: {
    tsearch: { prefix: true }
    }
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :book
  has_one_attached :photo
  validates :store, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :send_welcome_email
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :watch_lists, dependent: :destroy
  has_many :books, through: :watch_lists
  validates :email, presence: true, uniqueness: true

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/models/watch_list.rb
class WatchList < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    if params[:query].present?
      @books = Book.search_book(params[:query])
    elsif params[:language]
      @books = Book.where(language: params[:language])
    else
      @books = []
    end
  end

  def show
    @book = Book.find(params[:id])
    @watch_list = WatchList.new
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.includes(:book)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home
  end
end

app/controllers/watch_lists_controller.rb
class WatchListsController < ApplicationController
  def index
    @watch_lists = WatchList.where(user: current_user)
    @books = Book.all
  end

  def create
    @book = Book.find(params[:book_id])
    if current_user.watch_lists.where(book: @book).empty?
      @watch_list = WatchList.new(watch_list_params)
      @watch_list.book = @book
      @watch_list.user = current_user
      if @watch_list.save
        mail = WatchListMailer.with(watch_list: @watch_list).confirmation
        mail.deliver_now
        redirect_to watchlist_path
      else
        render :new
      end
    else
      redirect_to @book, notice: "Book already added"
    end
  end

  def destroy
    @watch_list = WatchList.find(params[:id])
    @watch_list.destroy

    redirect_to watchlist_path
  end

  private

  def watch_list_params
    params.require(:watch_list).permit(:target_price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="container-home">
  <div class="row">
    <div class="col-xl-12 col-md-12 col-sm-12">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1532012197267-da84d127e765?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1534&q=80);">

        <div class="container">
          <h1>Best prices</h1>
          <p>
            <span id="titulo"></span>
          </p>
        </div>
    


        <div class="container">
          <%=form_tag root_path, method: :get, class: "form-inline col-8 form-select" do %>
            <%= select_tag "query", options_from_collection_for_select(
              Book.all.order(:title), :author, :title, params[:query]), include_blank: true,
              class: 'select2' %>
            <%= submit_tag "Search", class: "btn btn-red my-2 my-sm-0 mx-2"  %>
          <% end %>
        </div>
      </div>  
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xl-12 col-md-12 col-sm-6">
      <p class="flag-title">Choose by language</p>
      <div class="flag">
        <%= link_to image_tag("espanha.png", size:"90"), root_path(language: "Español") %>
        <%= link_to image_tag("brazil.png", size:"90"), root_path(language: "Portuguese") %>
        <%= link_to image_tag("united-states.png", size:"90"), root_path(language: "English") %>
        <%= link_to image_tag("france.png", size:"90"), root_path(language: "Francês") %>
      </div>
    

      <div class="container">
        <div class="cards d-flex flex-wrap flex-row">
            <% @books.each do |book| %>
            <%= link_to book_path(book), class:"text-decoration-none" do %>
              <div class="one-card d-flex flex-sm-column row justify-content-center">
              <div class="col-12 text-center">
                  <%= cl_image_tag book.photo.key, height: 150, width: 150, crop: :pad, class: "mx-auto" if book.photo.attached? %>
                </div>
                <div class="col-12 text-center">
                  <span class="text-card"> <%= book.title %> </span>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container book-form my-5">
  <div class="card">
    <div class="row d-flex flex-wrap justify-content-center py-3">
      <div class=" col-12 col-md-3 d-flex justify-content-center">
        <%= cl_image_tag @book.photo.key, height: 350, width: 350, crop: :fit if @book.photo.attached? %>
      </div>

      <div class=" col-12 col-md-5 px-5">
        <div class="card-body justify-content">
          <h5 class="card-title"> <%= @book.title %> </h5>
          <p class="card-text"> <b> Language: </b> <%= @book.language %> </p>
          <p class="card-text"> <b> Author: </b> <%= @book.author %> </p>
          <p class="card-text description"> <b> Description: </b> <%= @book.description %> </p>
        </div>
      </div>

      <div class=" col-10 col-md-3 my-5 target w-75">
        <% if current_user && current_user.watch_lists.where(book: @book).empty? || !current_user %>
          <%= simple_form_for [@book, @watch_list] do |f| %>
            <b><%= f.input :target_price, label:"Price alert:", input_html: { min: '5.0' } %></b>
            <button type="submit" class="btn btn-red btn-target"> Add to list &#10084;</button>
          <% end %>
          <% else %>
           <p style="font-family: 'Caveat', cursive; font-weight: bold; font-size:30px;"> The book is already on your watch list! </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <% @book.deals.order(:price).each do |deal| %>
    <%= link_to deal.url, target: "_blank", style: "text-decoration: none;" do %>
      <div class="card-product row d-flex flex-nowrap align-items-center my-3 col-12 mx-auto" >
        <div class="col-md-3 col-5">
          <%= cl_image_tag deal.photo.key, height: 200, width: 200, crop: :fit, class:"img-fluid" if deal.photo.attached? %>
        </div>
        <div class="col-8 col-md-5 row d-flex align-items-center">
          <span class="color-price" >starting price $ <%= deal.price %> </span>
        </div>
        <!------ BOTÃO ------->
        <div class="col-1 col-md-4 d-flex flex-shrink-1 my-5 align-items-center justify-content-end">
          <span class="btn btn-red d-none d-md-block"> Store</span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/deals/index.html.erb
<div class="container">

<h1 >Deals Index</h1>

<% @deals.each do |deal| %>
  <p><%= deal.book.title %></p>
  <p><%= deal.book.price %></p>
  <p><%= deal.store %></p>
  <p>Your target price: <%= deal.price %></p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Compri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Caveat&family=Roboto:wght@300&family=Staatliches&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
    <div style="min-height:70vh;">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="https://github.com/waitoair/compri" target="_blank"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p> Final Project by Equipe Rocket 🚀 at Le Wagon</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container">
    <%= link_to  "Compri!", root_path, class:"navbar-brand" %>
    <div class="navbar navbar-expand-md" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://img.icons8.com/bubbles/452/book-reading.png", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Watch List", watchlist_path, class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/watch_lists/index.html.erb
<div class="container">
  <div class="align-items-center container-watch d-flex flex-column">
      <% @watch_lists.each_with_index do |watch_list, index| %>
        <div class="row">
          <div class="watch-book text-center">
            <p class="target-book"><%= watch_list.book.title %></p>
            <p class="target-your">Your target: <%= watch_list.target_price %></p>
            <div class="botao ml-2">
              <button id="cbtn-<%=index%>" class="btn btn-delete sweet-delete" data-index="<%=index%>"> Delete </button>
            </div>
            <%= link_to "Delete", watch_list_path(watch_list), method: :delete, id: "delete-#{index}", class: "invisible" %>
            <hr />
          </div>
        </div>
      <% end %>
  </div>
</div>